---
- name: Set keyboard layout
  ansible.builtin.lineinfile:
    path: '/etc/default/keyboard'
    regexp: '^{{ item.key }}='
    line: '{{ item.key }}="{{ item.value }}"'
  loop:
    - { key: "XKBLAYOUT", value: "{{ layout }}" }
    - { key: "XKBVARIANT", value: "{{ variant }}" }
  become: true
