---
- name: Install gcc and g++ 12
  ansible.builtin.apt:
    name:
      - gcc-12
      - g++-12
  become: true

- name: Add alternatives for gcc and g++
  community.general.alternatives:
    name: "{{ item.name }}"
    link: "{{ item.link }}"
    path: "{{ item.path }}"
    priority: "{{ item.priority }}"
  loop:
    - { name: "gcc", link: "/usr/bin/gcc", path: /usr/bin/gcc-11, priority: 10 }
    - { name: "gcc", link: "/usr/bin/gcc", path: /usr/bin/gcc-12, priority: 20 }
    - { name: "g++", link: "/usr/bin/g++", path: /usr/bin/g++-11, priority: 10 }
    - { name: "g++", link: "/usr/bin/g++", path: /usr/bin/g++-12, priority: 20 }
  become: true
