---
- name: Install vim and ycm requirements
  apt:
    name:
      - vim
      - python3
      - gcc
      - python3-pip
  become:  true

- name: Install additional dependencies of vim configuration
  pip:
    name:
      - cmake
      - black
      - flake8
      - pylint
      - gitpython

- name: Create vim config directories
  file:
    path: "{{ ansible_env.HOME }}/{{ item.path }}"
    state: directory
  with_filetree: "config"
  when: item.state == "directory"

- name: Copy vim config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.path }}"
  with_filetree: "config"
  when: item.state == 'file'
