---
- name: Install vim and ycm requirements
  ansible.builtin.apt:
    name:
      - vim
      - python3
      - gcc
      - python3-pip
  become: true

- name: Install additional dependencies of vim configuration
  ansible.builtin.pip:
    name:
      - cmake
      - black
      - flake8
      - pylint
      - gitpython

- name: Create vim config directories
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  with_filetree: ./
  when: item.state == "directory"

- name: Copy vim config files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.path }}"
    mode: preserve
  with_filetree: ./
  when: item.state == 'file'
