---
- name: Install gpg
  ansible.builtin.apt:
    name: "gpg"
  become: true

- name: Copy gpg config
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/.gnupg/"
    mode: preserve
  with_filetree: "./"
